### PR TITLE
Remove boss block

### PR DESCRIPTION
**Pull request by L-e-x-o-n**

### CODE REVIEW

**Review by geekingfrog — APPROVED** [review]
out of curiosity, why are we removing that?

**Comment by jauggy** [comment]
I'm guessing Lexon must have been blocked by someone :P

I do suggest you consider either these PRs as they still allow people who want full control over their lobbies:

Hijacked lobbies don't apply boss blocks:
https://github.com/beyond-all-reason/teiserver/pull/364

Only custom preset lobbies allow boss blocks.
https://github.com/beyond-all-reason/teiserver/pull/372

**Comment by L-e-x-o-n** [comment]
I have never been affected by this feature.
I think the idea is good but multiple people raised some good potential issues woth it.
I just prepared the work and was planning to leave it to GDT or someone else to decide what to do with it.

Jauggy now reminded me of those other PRs and I think thats a much better solution so I am closing this now.

**Comment by L-e-x-o-n** [comment]
Sorry @jauggy, not sure how I missed your earlier PRs on this topic.

**Pull request closed without merging**
