### PR TITLE
Report form adjustments - required description

### PR DESCRIPTION
**Pull request by StanczakDominik**
This makes the description field required for reports and adjusts the wording a little so that the information provided is a little more helpful :)

### CODE REVIEW

**Comment by Teifion** [comment]
This doesn't force there to be a description in those cases, I'd like to see server-side logic enforcing this.

**Comment by StanczakDominik** [comment]
You're right, sorry. I'm a bit of a newbie to web dev and, come to think of it, I think I've seen this exact approach as a meme on r/programmerhumor. I'll figure it out :)

**Comment by Teifion** [comment]
@StanczakDominik Does this need to be open?

**Comment by StanczakDominik** [comment]
Not at all, thanks for the reminder!

**Pull request closed without merging**
