### PR TITLE
Display uncertainy values for each match

### PR DESCRIPTION
**Pull request by Jordan-Cottle**
## Summary

This PR adds in the `uncertainty` and `uncertainty_change` values to the match rating table so that players can know what their uncertainty was and how much each match impacted their uncertainty values.

I've chosen to not highlight the change values red/green because uncertainty changes aren't inherently good/bad, and the value should only really go down over time.

relates to #255 (and might close it if this is deemed sufficient to resolve the confusion)

## Test Evidence

image

### CODE REVIEW

**Comment by jauggy** [comment]
@Jordan-Cottle sorry I updated the ticket as you were working on it. Can you do it as a hover over tooltip? Show people the `skill-uncertainty`

Keep the columns the same. The main purpose is for people who have match rating 0.0 so it's not useful information except for those people.

**Comment by jauggy** [comment]
The idea is so that this person here could hover over their 0.0 number and see what the skill-uncertainty is. Not sure exactly would the tooltip should say. It could show 3 numbers or just 1. I'll need to see.

**Comment by Jordan-Cottle** [comment]
I'd need to figure out how to do a tooltip, but I'm guessing fontawesome might have a css class for it already?

Happy to make the change to a tooltip if needed, but I actually kind of like the additional column. 

I use this page myself a lot, and often felt like it didn't answer the "What is my uncertainty though?" question very well. So I know I'd personally be interested in having the uncertainty for each match displayed here and I'm not a player with a negative match rating.

**Comment by Jordan-Cottle** [comment]
Also, I don't think negative match rating is a thing. It looks like everywhere match rating is calculated teiserver is pinning the min at 0.

Example: https://github.com/beyond-all-reason/teiserver/blob/324ba2b0a0e50c82feb3f86eeffbd7db626a2d37/lib/teiserver/battle/libs/balance_lib.ex#L505

**Comment by jauggy** [comment]
Negative match rating is not a thing. So the tooltip is showing `skill-uncertainty`. Not their match rating. It's useful so that someone can see this value changing rather than staying at 0.

For the uncertainty column, if you really want it, can you change the diff column to be colour coded like the others?

**Comment by Jordan-Cottle** [comment]
Yup, I had the diff column color coded at first. But since up/down of uncertainty isn't obviously good (green) or bad (red) I thought the colors might be misleading. If I make down red, then players might think they're doing something wrong if their uncertainty keeps decreasing.

Also, if uncertainty never goes up due to a match, the other color would never show up and the red color would effectively just be an additional highlight to distract from the more important numbers.

What if I just add the up/down icon and not the color coding?

**Comment by jauggy** [comment]
Can I see what it looks like colored and with arrows? For me the colors just let me know that it's a delta not an absolute value. But maybe if you show me what it looks like I'll have a better idea.

Also for some reason the arrows disappeared on the other columns. If it's due to FontAwesome, try and find a free arrow since Marek wanted us to not depend on paid version.

**Comment by Jordan-Cottle** [comment]
Sure!

I've added in the color code and arrows to the uncertainty change column. I also updated the icon to use a free version of the up/down arrows.

image


If you like it, I'll update the test evidence in the initial PR description to show this version

**Comment by Jordan-Cottle** [comment]
And this is what it looks like with the arrows, but not colored

image

**Pull request merged**
