### PR TITLE
Add replay page button on match overview page

### PR DESCRIPTION
**Pull request by L-e-x-o-n**

### CODE REVIEW

**Review by StanczakDominik — APPROVED** [review]
Aw hell yeah.

**Comment by L-e-x-o-n** [comment]
This is still work in progress.
For this to work for older matches I plan to add a new column in `teiserver_battle_matches` table called `game_id` containing `gameId` from `data`. Currently the cleanup task removes data for older matches as part of the cleanup task.

@p2004a this might be of interest to you, potentially useful for https://github.com/beyond-all-reason/data-processing ?

(Jazcash already added a button linking to Teiserver on the [replays page](https://www.beyondallreason.info/replays?gameId=eef103670e79a7159f67e52e3d1aa44e))

**Comment by jauggy** [comment]
@L-e-x-o-n if I am developing locally with an older database schema, do I need to run a command to update the schema?

**Comment by L-e-x-o-n** [comment]
> @L-e-x-o-n if I am developing locally with an older database schema, do I need to run a command to update the schema? Should I just run `mix ecto.migrate` ?

Yes

**Pull request merged**
