### PR TITLE
removed min limit (1) for shown skills to spads

### PR DESCRIPTION
**Pull request by FIr3baL**

### CODE REVIEW

**Comment by FIr3baL** [comment]
this should be testet with webserver, too!
AS i learned now, values from spads go into demo files and those are used as origin for website values.

**Comment by Beherith** [comment]
@FIr3baL scream if this can go in

**Comment by jauggy** [comment]
Currently on the website ratings page 
```
https://server4.beyondallreason.info/profile/157348
```
The match rating will floor at 0.0 if your `skill-uncertainty` is negative. Similarly the database ratin value will floor at 0.0. $whoami rating stats also will floor at 0.0. 

But Chobby currently shows 1 as the OS floor. This PR would make things consistent with the true value.

**Comment by FIr3baL** [comment]
@jauggy thanks for testing.
@Beherith imho, this can go in !

**Pull request merged**
